### ISSUE TITLE
starting the plugin -> python error

### ISSUE THREAD

**Issue by ThomasStruller** [givaldocesar/amil#3]
Hallo,
thank you for developing your extenstion for Qgis. Tried to start it, but got the following python fault:

2022-01-11T11:04:05     WARNING    Traceback (most recent call last):
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil.py", line 190, in run
              self.dlg = AmilDialog(self.iface)
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 131, in __init__
              self.projectChanged()
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 632, in projectChanged
              self.addLayersToList(self.project.mapLayers())
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 191, in addLayersToList
              self.layers.append(PolygonLayer(layer, count))
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 169, in __init__
              self.setSymbology(VectorLayer)
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 94, in setSymbology
              self.symbology = {'symbol': self.style(layer, symbol)}
              File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 175, in style
              'weight': convertWeight(symbol['outline_width']),
             KeyError: 'outline_width'

hopes that helps you

**Comment by givaldocesar** [comment]
hello, I'm grateful for your feedback, I'm hospitalized at the moment, as soon as I get back, I'll correct the error.Em 11 de jan. de 2022 07:10, ThomasStruller ***@***.***> escreveu:
Hallo,
thank you for developing your extenstion for Qgis. Tried to start it, but got the following python fault:
2022-01-11T11:04:05     WARNING    Traceback (most recent call last):
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil.py", line 190, in run
self.dlg = AmilDialog(self.iface)
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 131, in init
self.projectChanged()
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 632, in projectChanged
self.addLayersToList(self.project.mapLayers())
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\amil_dialog.py", line 191, in addLayersToList
self.layers.append(PolygonLayer(layer, count))
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 169, in init
self.setSymbology(VectorLayer)
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 94, in setSymbology
self.symbology = {'symbol': self.style(layer, symbol)}
File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\amil\objects.py", line 175, in style
'weight': convertWeight(symbol['outline_width']),
KeyError: 'outline_width'
hopes that helps you
